### ISSUE TITLE
Working on the mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_2_TOOL/SS_2_TOOL.obj /usr/bin/xvfb-run: 184: None: not found

### ISSUE THREAD

**Issue by monajalal** [ponimatkin/focalpose#7]
I followed all the instructions for data download and preparation, however, I got this error. Could you please help me how to fix it or what's missing?

```
focalpose) mona@ard-gpu-01:~/focalpose$ bash preprocess_data.sh

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Setting OMP and MKL num threads to 1.
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/focalpose/focalpose/scripts/cars_to_urdf.py", line 74, in <module>
    copy2(obj.as_posix(), obj.with_name(f'{cls.name}').with_suffix('.obj'))
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/mona/focalpose/local_data/StanfordCars/models/eaeabed4e984364868ebd0cfefbb61e9/eaeabed4e984364868ebd0cfefbb61e9.obj' and PosixPath('/home/mona/focalpose/local_data/StanfordCars/models/eaeabed4e984364868ebd0cfefbb61e9/eaeabed4e984364868ebd0cfefbb61e9.obj') are the same file
Setting OMP and MKL num threads to 1.
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/focalpose/focalpose/scripts/pix3d_to_urdf.py", line 77, in <module>
    copy2(files.as_posix(), files.with_name(f'{obj.name}_{cls.name.upper()}').with_suffix('.obj'))
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/mona/focalpose/local_data/pix3d/model/tool/SS_3/SS_3_TOOL.obj' and PosixPath('/home/mona/focalpose/local_data/pix3d/model/tool/SS_3/SS_3_TOOL.obj') are the same file
Setting OMP and MKL num threads to 1.
100%|███████████████████████████████████████| 8144/8144 [01:53<00:00, 71.71it/s]
100%|███████████████████████████████████████| 8041/8041 [01:53<00:00, 71.04it/s]
Setting OMP and MKL num threads to 1.
100%|███████████████████████████████████████| 3798/3798 [00:59<00:00, 63.97it/s]
100%|███████████████████████████████████████| 1898/1898 [00:30<00:00, 62.83it/s]
Setting OMP and MKL num threads to 1.
Working on the mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_2_TOOL/SS_2_TOOL.obj
/usr/bin/xvfb-run: 184: None: not found
Generating empty texture for mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_2_TOOL/SS_2_TOOL.obj
/usr/bin/xvfb-run: 184: None: not found
Working on the mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_5_TOOL/SS_5_TOOL.obj
/usr/bin/xvfb-run: 184: None: not found
Generating empty texture for mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_5_TOOL/SS_5_TOOL.obj
/usr/bin/xvfb-run: 184: None: not found
Working on the mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_7_TOOL/SS_7_TOOL.obj
/usr/bin/xvfb-run: 184: None: not found
Generating empty texture for mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_7_TOOL/SS_7_TOOL.obj
/usr/bin/xvfb-run: 184: None: not found
Working on the mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_8_TOOL/SS_8_TOOL.obj
/usr/bin/xvfb-run: 184: None: not found
Generating empty texture for mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_8_TOOL/SS_8_TOOL.obj
/usr/bin/xvfb-run: 184: None: not found
Working on the mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_6_TOOL/SS_6_TOOL.obj
/usr/bin/xvfb-run: 184: None: not found


and so on

```

**Comment by monajalal** [comment]
my bad

the fix:
```

(base) mona@ard-gpu-01:~/focalpose$ cat config.yaml
slurm_gpu_queue: 'gpu'
slurm_qos:
dask_network_interface: 'eth0'
meshlab_path: '/snap/bin/meshlab'
```
