### ISSUE TITLE
Shader directory found '/snap/meshlab/183/usr/bin/shaders', and it contains 0 gdp files

### ISSUE THREAD

**Issue by monajalal** [ponimatkin/focalpose#8]
Is this something to be considered about and if so, what do you suggest as a fix?

```
(focalpose) mona@ard-gpu-01:~/focalpose$ bash preprocess_data.sh
Setting OMP and MKL num threads to 1.
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/focalpose/focalpose/scripts/cars_to_urdf.py", line 74, in <module>
    copy2(obj.as_posix(), obj.with_name(f'{cls.name}').with_suffix('.obj'))
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/mona/focalpose/local_data/StanfordCars/models/eaeabed4e984364868ebd0cfefbb61e9/eaeabed4e984364868ebd0cfefbb61e9.obj' and PosixPath('/home/mona/focalpose/local_data/StanfordCars/models/eaeabed4e984364868ebd0cfefbb61e9/eaeabed4e984364868ebd0cfefbb61e9.obj') are the same file
Setting OMP and MKL num threads to 1.
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/focalpose/focalpose/scripts/pix3d_to_urdf.py", line 77, in <module>
    copy2(files.as_posix(), files.with_name(f'{obj.name}_{cls.name.upper()}').with_suffix('.obj'))
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/mona/focalpose/local_data/pix3d/model/tool/SS_3/SS_3_TOOL.obj' and PosixPath('/home/mona/focalpose/local_data/pix3d/model/tool/SS_3/SS_3_TOOL.obj') are the same file
Setting OMP and MKL num threads to 1.
100%|███████████████████████████████████████| 8144/8144 [01:54<00:00, 71.41it/s]
100%|███████████████████████████████████████| 8041/8041 [01:52<00:00, 71.73it/s]
Setting OMP and MKL num threads to 1.
100%|███████████████████████████████████████| 3798/3798 [00:59<00:00, 63.31it/s]
100%|███████████████████████████████████████| 1898/1898 [00:30<00:00, 61.63it/s]
Setting OMP and MKL num threads to 1.
Working on the mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_2_TOOL/SS_2_TOOL.obj
Qt: Session management error: Could not open network socket
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.1108\" (uid=1002 pid=176867 comm=\"/snap/meshlab/183/usr/bin/meshlab -i /home/mona/fo\" label=\"snap.meshlab.meshlab (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=827 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.1108\" (uid=1002 pid=176867 comm=\"/snap/meshlab/183/usr/bin/meshlab -i /home/mona/fo\" label=\"snap.meshlab.meshlab (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=827 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
Shader directory found '/snap/meshlab/183/usr/bin/shaders', and it contains 0 gdp files
Shader directory found '/snap/meshlab/183/usr/bin/shaders', and it contains 0 gdp files

```

**Comment by ponimatkin** [comment]
Hi, I've never ran Focalpose on Ubuntu (only RHEL systems), but could you please try to install MeshLab AppImage from here https://www.meshlab.net/#download and try it?

**Comment by monajalal** [comment]
Thanks a lot. It worked.

Do you know how long does it take approximately for this script to finish? Also are the two errors seen beginning of the script OK?

```
(focalpose) mona@ard-gpu-01:~/focalpose$ bash preprocess_data.sh
Setting OMP and MKL num threads to 1.
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/focalpose/focalpose/scripts/cars_to_urdf.py", line 74, in <module>
    copy2(obj.as_posix(), obj.with_name(f'{cls.name}').with_suffix('.obj'))
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/mona/focalpose/local_data/StanfordCars/models/eaeabed4e984364868ebd0cfefbb61e9/eaeabed4e984364868ebd0cfefbb61e9.obj' and PosixPath('/home/mona/focalpose/local_data/StanfordCars/models/eaeabed4e984364868ebd0cfefbb61e9/eaeabed4e984364868ebd0cfefbb61e9.obj') are the same file
Setting OMP and MKL num threads to 1.
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/focalpose/focalpose/scripts/pix3d_to_urdf.py", line 77, in <module>
    copy2(files.as_posix(), files.with_name(f'{obj.name}_{cls.name.upper()}').with_suffix('.obj'))
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/mona/focalpose/local_data/pix3d/model/tool/SS_3/SS_3_TOOL.obj' and PosixPath('/home/mona/focalpose/local_data/pix3d/model/tool/SS_3/SS_3_TOOL.obj') are the same file
Setting OMP and MKL num threads to 1.
100%|██████████████████████████████████████| 8144/8144 [01:19<00:00, 102.63it/s]
100%|███████████████████████████████████████| 8041/8041 [01:21<00:00, 99.15it/s]
Setting OMP and MKL num threads to 1.
100%|███████████████████████████████████████| 3798/3798 [00:43<00:00, 88.16it/s]
100%|███████████████████████████████████████| 1898/1898 [00:21<00:00, 88.08it/s]
Setting OMP and MKL num threads to 1.
Working on the mesh: /home/mona/focalpose/local_data/models_urdf/pix3d/tool/SS_2_TOOL/SS_2_TOOL.obj
Using OpenGL 4.5

```

**Comment by monajalal** [comment]
As you can see the command is kinda stuck here so it would be great to know what we are expecting as there's no output or progress bar.

![image](https://user-images.githubusercontent.com/1892917/218860242-195b6f39-1523-485c-a082-9ae6a0a786bd.png)

**Comment by ponimatkin** [comment]
Hi with respect to the issue in #6  it is a bit weird to see this error, since I don't recall seeing it. The issue is caused by this line: https://github.com/ponimatkin/focalpose/blob/db1363ee2c87e499caf5df1305d428f3de71413b/focalpose/scripts/cars_to_urdf.py#L74. In essence, the script creates a copy of the obj file and then makes URDF using it. I'm not sure why it happens. You may want to fix it using something like that: https://stackoverflow.com/questions/57083594/disable-samefileerror-exception-in-shutil-copy

As for the last part, `focalpose.scripts.patch_uv` is a hacky script created to pach uv maps of some 3D models using meshlab as some of them have troubles. But you can skip this step, it is not mandatory.
